##Create cliffs=name
##formulaforextractcliffsfromslope=string1*(A>25)
##minimumareaofcliffmeters2=string18
##digitalelevationmodel=raster
##maximumdistancemetersbetweentheoriginalandthesimplifiedcurvedouglaspeuckeralgorithm=number3
##distancemetersbetweenthecreatedpointshermitesplineinterpolation=number3
##maximumareaofcliffmeters=string500
##minimumanglebetweentwoconsecutivesegmentsinhermitesplineinterpolation=number3
##cliffs=output vector
outputs_GDALOGRSLOPE_1=processing.runalg('gdalogr:slope', digitalelevationmodel,1.0,False,False,False,1.0,None)
outputs_GDALOGRRASTERCALCULATOR_1=processing.runalg('gdalogr:rastercalculator', outputs_GDALOGRSLOPE_1['OUTPUT'],'1',None,'1',None,'1',None,'1',None,'1',None,'1',formulaforextractcliffsfromslope,None,5,None,None)
outputs_GDALOGRPOLYGONIZE_1=processing.runalg('gdalogr:polygonize', outputs_GDALOGRRASTERCALCULATOR_1['OUTPUT'],'DN',None)
outputs_QGISEXTRACTBYATTRIBUTE_1=processing.runalg('qgis:extractbyattribute', outputs_GDALOGRPOLYGONIZE_1['OUTPUT'],'DN',2,'0',None)
outputs_QGISFIELDCALCULATOR_1=processing.runalg('qgis:fieldcalculator', outputs_QGISEXTRACTBYATTRIBUTE_1['OUTPUT'],'area',0,10.0,3.0,True,'$area',None)
outputs_QGISEXTRACTBYATTRIBUTE_2=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_1['OUTPUT_LAYER'],'area',3,minimumareaofcliffmeters2,None)
outputs_QGISEXTRACTBYATTRIBUTE_3=processing.runalg('qgis:extractbyattribute', outputs_QGISEXTRACTBYATTRIBUTE_2['OUTPUT'],'area',5,maximumareaofcliffmeters,None)
outputs_QGISFILLHOLES_1=processing.runalg('qgis:fillholes', outputs_QGISEXTRACTBYATTRIBUTE_3['OUTPUT'],100000.0,None)
outputs_QGISPOLYGONSTOLINES_1=processing.runalg('qgis:polygonstolines', outputs_QGISFILLHOLES_1['Results'],None)
outputs_GRASS7V.GENERALIZE.SIMPLIFY_1=processing.runalg('grass7:v.generalize.simplify', outputs_QGISPOLYGONSTOLINES_1['OUTPUT'],0,1.0,maximumdistancemetersbetweentheoriginalandthesimplifiedcurvedouglaspeuckeralgorithm,50.0,False,True,None,-1.0,0.0001,0,None)
outputs_GRASS7V.GENERALIZE.SMOOTH_1=processing.runalg('grass7:v.generalize.smooth', outputs_GRASS7V.GENERALIZE.SIMPLIFY_1['output'],4,distancemetersbetweenthecreatedpointshermitesplineinterpolation,7.0,0.5,minimumanglebetweentwoconsecutivesegmentsinhermitesplineinterpolation,1.0,1.0,False,True,None,-1.0,0.0001,0,None)
outputs_QGISLINESTOPOLYGONS_1=processing.runalg('qgis:linestopolygons', outputs_GRASS7V.GENERALIZE.SMOOTH_1['output'],cliffs)