##Create small knolls and form lines of knolls=name
##formulatodistinguishknollsandauxiliarycontours=stringif((Round("area"))<=22,1,2)
##halfdistancebetweenthecentersoftwoknollsmeters=number3.0
##maximalradiusofknollmeters=number13.5
##dem=raster
##formlinesknolls=output vector
##knolls=output vector
outputs_SAGAINVERTGRID_1=processing.runalg('saga:invertgrid', dem,None)
outputs_MODELERFIND-DEPRESSION-AREA_1=processing.runalg('modeler:find-depression-area', outputs_SAGAINVERTGRID_1['INVERSE'],None)
outputs_QGISFIELDCALCULATOR_1=processing.runalg('qgis:fieldcalculator', outputs_MODELERFIND-DEPRESSION-AREA_1['OUTPUT_ALGQGISEXTRACTBYATTRIBUTE_1'],'area',0,10.0,1.0,True,'$area',None)
outputs_QGISEXTRACTBYATTRIBUTE_2=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_1['OUTPUT_LAYER'],'area',2,'4',None)
outputs_QGISEXTRACTBYATTRIBUTE_1=processing.runalg('qgis:extractbyattribute', outputs_QGISEXTRACTBYATTRIBUTE_2['OUTPUT'],'area',5,'109',None)
outputs_QGISDISSOLVE_1=processing.runalg('qgis:dissolve', outputs_QGISEXTRACTBYATTRIBUTE_1['OUTPUT'],True,None,None)
outputs_QGISPOLYGONSTOLINES_1=processing.runalg('qgis:polygonstolines', outputs_QGISDISSOLVE_1['OUTPUT'],None)
outputs_QGISLINESTOPOLYGONS_1=processing.runalg('qgis:linestopolygons', outputs_QGISPOLYGONSTOLINES_1['OUTPUT'],None)
outputs_QGISFIELDCALCULATOR_2=processing.runalg('qgis:fieldcalculator', outputs_QGISLINESTOPOLYGONS_1['OUTPUT'],'area',0,10.0,1.0,False,'$area',None)
outputs_QGISEXTRACTBYATTRIBUTE_3=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_2['OUTPUT_LAYER'],'area',5,'109',None)
outputs_QGISPOLYGONCENTROIDS_1=processing.runalg('qgis:polygoncentroids', outputs_QGISEXTRACTBYATTRIBUTE_3['OUTPUT'],None)
outputs_QGISFIXEDDISTANCEBUFFER_1=processing.runalg('qgis:fixeddistancebuffer', outputs_QGISPOLYGONCENTROIDS_1['OUTPUT_LAYER'],maximalradiusofknollmeters,5.0,False,None)
outputs_QGISEXTRACTBYLOCATION_1=processing.runalg('qgis:extractbylocation', outputs_QGISEXTRACTBYATTRIBUTE_3['OUTPUT'],outputs_QGISFIXEDDISTANCEBUFFER_1['OUTPUT'],['within'],1.0,None)
outputs_QGISFIELDCALCULATOR_3=processing.runalg('qgis:fieldcalculator', outputs_QGISEXTRACTBYLOCATION_1['OUTPUT'],'type',1,1.0,0.0,True,formulatodistinguishknollsandauxiliarycontours,None)
outputs_QGISEXTRACTBYATTRIBUTE_5=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_3['OUTPUT_LAYER'],'type',0,'2',None)
outputs_QGISEXTRACTBYATTRIBUTE_4=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_3['OUTPUT_LAYER'],'type',0,'1',None)
outputs_QGISPOLYGONSTOLINES_2=processing.runalg('qgis:polygonstolines', outputs_QGISEXTRACTBYATTRIBUTE_5['OUTPUT'],formlinesknolls)
outputs_SAGAPOLYGONCENTROIDS_1=processing.runalg('saga:polygoncentroids', outputs_QGISEXTRACTBYATTRIBUTE_4['OUTPUT'],True,None)
outputs_QGISFIXEDDISTANCEBUFFER_2=processing.runalg('qgis:fixeddistancebuffer', outputs_SAGAPOLYGONCENTROIDS_1['CENTROIDS'],halfdistancebetweenthecentersoftwoknollsmeters,5.0,False,None)
outputs_QGISDISSOLVE_2=processing.runalg('qgis:dissolve', outputs_QGISFIXEDDISTANCEBUFFER_2['OUTPUT'],True,None,None)
outputs_QGISPOLYGONSTOLINES_3=processing.runalg('qgis:polygonstolines', outputs_QGISDISSOLVE_2['OUTPUT'],None)
outputs_QGISLINESTOPOLYGONS_2=processing.runalg('qgis:linestopolygons', outputs_QGISPOLYGONSTOLINES_3['OUTPUT'],None)
outputs_QGISPOLYGONCENTROIDS_2=processing.runalg('qgis:polygoncentroids', outputs_QGISLINESTOPOLYGONS_2['OUTPUT'],knolls)