##Create large boulders=name
##formulaforextractcliffsfromslope=string1*(A>20)
##halfdistancebetweenthecentersofthetwobouldersmeters=number6.0
##minimumareaofcliffmeters2=string5
##digitalelevationmodel=raster
##maximumareaofcliffmeters=string144
##themaximumdistancebetweenthecenterandtheedgeofthebouldermeters=number6.0
##largeboulders=output vector
outputs_GDALOGRSLOPE_1=processing.runalg('gdalogr:slope', digitalelevationmodel,1.0,False,False,False,1.0,None)
outputs_GDALOGRRASTERCALCULATOR_1=processing.runalg('gdalogr:rastercalculator', outputs_GDALOGRSLOPE_1['OUTPUT'],'1',None,'1',None,'1',None,'1',None,'1',None,'1',formulaforextractcliffsfromslope,None,5,None,None)
outputs_GDALOGRPOLYGONIZE_1=processing.runalg('gdalogr:polygonize', outputs_GDALOGRRASTERCALCULATOR_1['OUTPUT'],'DN',None)
outputs_QGISEXTRACTBYATTRIBUTE_1=processing.runalg('qgis:extractbyattribute', outputs_GDALOGRPOLYGONIZE_1['OUTPUT'],'DN',2,'0',None)
outputs_QGISFIELDCALCULATOR_1=processing.runalg('qgis:fieldcalculator', outputs_QGISEXTRACTBYATTRIBUTE_1['OUTPUT'],'area',0,10.0,3.0,True,'$area',None)
outputs_QGISEXTRACTBYATTRIBUTE_2=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_1['OUTPUT_LAYER'],'area',3,minimumareaofcliffmeters2,None)
outputs_QGISEXTRACTBYATTRIBUTE_3=processing.runalg('qgis:extractbyattribute', outputs_QGISEXTRACTBYATTRIBUTE_2['OUTPUT'],'area',5,maximumareaofcliffmeters,None)
outputs_QGISPOLYGONCENTROIDS_2=processing.runalg('qgis:polygoncentroids', outputs_QGISEXTRACTBYATTRIBUTE_3['OUTPUT'],None)
outputs_QGISFILLHOLES_1=processing.runalg('qgis:fillholes', outputs_QGISEXTRACTBYATTRIBUTE_3['OUTPUT'],100000.0,None)
outputs_QGISFIXEDDISTANCEBUFFER_1=processing.runalg('qgis:fixeddistancebuffer', outputs_QGISPOLYGONCENTROIDS_2['OUTPUT_LAYER'],themaximumdistancebetweenthecenterandtheedgeofthebouldermeters,5.0,False,None)
outputs_QGISDIFFERENCE_1=processing.runalg('qgis:difference', outputs_QGISFILLHOLES_1['Results'],outputs_QGISEXTRACTBYATTRIBUTE_3['OUTPUT'],True,None)
outputs_QGISPOLYGONCENTROIDS_1=processing.runalg('qgis:polygoncentroids', outputs_QGISDIFFERENCE_1['OUTPUT'],None)
outputs_QGISFIXEDDISTANCEBUFFER_2=processing.runalg('qgis:fixeddistancebuffer', outputs_QGISPOLYGONCENTROIDS_1['OUTPUT_LAYER'],1.0,5.0,False,None)
outputs_QGISEXTRACTBYLOCATION_1=processing.runalg('qgis:extractbylocation', outputs_QGISFIXEDDISTANCEBUFFER_1['OUTPUT'],outputs_QGISFIXEDDISTANCEBUFFER_2['OUTPUT'],['intersects'],1.0,None)
outputs_QGISEXTRACTBYATTRIBUTE_4=processing.runalg('qgis:extractbyattribute', outputs_QGISEXTRACTBYLOCATION_1['OUTPUT'],'DN',3,'0',None)
outputs_QGISFIXEDDISTANCEBUFFER_3=processing.runalg('qgis:fixeddistancebuffer', outputs_QGISEXTRACTBYATTRIBUTE_4['OUTPUT'],halfdistancebetweenthecentersofthetwobouldersmeters,5.0,False,None)
outputs_QGISDISSOLVE_1=processing.runalg('qgis:dissolve', outputs_QGISFIXEDDISTANCEBUFFER_3['OUTPUT'],True,None,None)
outputs_QGISPOLYGONSTOLINES_1=processing.runalg('qgis:polygonstolines', outputs_QGISDISSOLVE_1['OUTPUT'],None)
outputs_QGISLINESTOPOLYGONS_1=processing.runalg('qgis:linestopolygons', outputs_QGISPOLYGONSTOLINES_1['OUTPUT'],None)
outputs_QGISPOLYGONCENTROIDS_3=processing.runalg('qgis:polygoncentroids', outputs_QGISLINESTOPOLYGONS_1['OUTPUT'],largeboulders)