##Create water area (LIDAR points)=name
##radiusdensityestimation=number5.0
##densityestimationcellsize=number2.0
##minimumareaofthewaterarea=string500
##maximaltolerancevaluevgeneralizesmooth=number2
##lidarpoints=vector
##tolerancesimplifygeometries=number2
##enlargeofpolygonofthewaterareameters=number5.0
##waterarea=output vector
outputs_SAGAKERNELDENSITYESTIMATION_1=processing.runalg('saga:kerneldensityestimation', lidarpoints,'1',radiusdensityestimation,0,None,densityestimationcellsize,0,None)
outputs_SAGAINVERTDATANODATA_1=processing.runalg('saga:invertdatanodata', outputs_SAGAKERNELDENSITYESTIMATION_1['TARGET_OUT_GRID'],None)
outputs_GDALOGRPOLYGONIZE_1=processing.runalg('gdalogr:polygonize', outputs_SAGAINVERTDATANODATA_1['OUTPUT'],'DN',None)
outputs_QGISFIELDCALCULATOR_1=processing.runalg('qgis:fieldcalculator', outputs_GDALOGRPOLYGONIZE_1['OUTPUT'],'area',0,10.0,3.0,True,'$area',None)
outputs_QGISEXTRACTBYATTRIBUTE_1=processing.runalg('qgis:extractbyattribute', outputs_QGISFIELDCALCULATOR_1['OUTPUT_LAYER'],'area',3,minimumareaofthewaterarea,None)
outputs_QGISFILLHOLES_1=processing.runalg('qgis:fillholes', outputs_QGISEXTRACTBYATTRIBUTE_1['OUTPUT'],10000.0,None)
outputs_QGISFIXEDDISTANCEBUFFER_1=processing.runalg('qgis:fixeddistancebuffer', outputs_QGISFILLHOLES_1['Results'],enlargeofpolygonofthewaterareameters,5.0,False,None)
outputs_QGISFILLHOLES_2=processing.runalg('qgis:fillholes', outputs_QGISFIXEDDISTANCEBUFFER_1['OUTPUT'],1000.0,None)
outputs_QGISSIMPLIFYGEOMETRIES_1=processing.runalg('qgis:simplifygeometries', outputs_QGISFILLHOLES_2['Results'],tolerancesimplifygeometries,None)
outputs_GRASS7V.GENERALIZE.SMOOTH_1=processing.runalg('grass7:v.generalize.smooth', outputs_QGISSIMPLIFYGEOMETRIES_1['OUTPUT'],3,maximaltolerancevaluevgeneralizesmooth,7.0,0.5,3.0,1.0,1.0,False,True,None,-1.0,0.0001,0,waterarea)