##Create roads, paths (OSM)=name
##layerofroadsways=vector
##expressionforextractfootpathfromosmbyattribute=string"fclass" IN ('track_grade4','track_grade5')
##expressionforextractsmallfootpathfromosmbyattribute=string"fclass" IN ('path','footway')
##expressionforextractvehicletrackfromosmbyattribute=string"fclass" IN ('track_grade3')
##expressionforextractroadfromosmbyattribute=string"fclass" IN ('track_grade1','track_grade2')
##expressionforextractwideroadfromosmbyattribute=string"fclass" IN ('primary','secondary','tertiary','trunk', 'motorway', 'service', 'unclassified', 'living_street', 'pedestrian')
##road=output vector
##vehicletrack=output vector
##wideroad=output vector
##footpath=output vector
##smallfootpath=output vector
outputs_QGISSELECTBYEXPRESSION_1=processing.runalg('qgis:selectbyexpression', layerofroadsways,expressionforextractwideroadfromosmbyattribute,0)
outputs_QGISSAVESELECTEDFEATURES_1=processing.runalg('qgis:saveselectedfeatures', outputs_QGISSELECTBYEXPRESSION_1['RESULT'],wideroad)
outputs_QGISSELECTBYEXPRESSION_2=processing.runalg('qgis:selectbyexpression', layerofroadsways,expressionforextractroadfromosmbyattribute,0)
outputs_QGISSAVESELECTEDFEATURES_2=processing.runalg('qgis:saveselectedfeatures', outputs_QGISSELECTBYEXPRESSION_2['RESULT'],road)
outputs_QGISSELECTBYEXPRESSION_3=processing.runalg('qgis:selectbyexpression', layerofroadsways,expressionforextractvehicletrackfromosmbyattribute,0)
outputs_QGISSAVESELECTEDFEATURES_3=processing.runalg('qgis:saveselectedfeatures', outputs_QGISSELECTBYEXPRESSION_3['RESULT'],vehicletrack)
outputs_QGISSELECTBYEXPRESSION_4=processing.runalg('qgis:selectbyexpression', layerofroadsways,expressionforextractfootpathfromosmbyattribute,0)
outputs_QGISSAVESELECTEDFEATURES_4=processing.runalg('qgis:saveselectedfeatures', outputs_QGISSELECTBYEXPRESSION_4['RESULT'],footpath)
outputs_QGISSELECTBYEXPRESSION_5=processing.runalg('qgis:selectbyexpression', layerofroadsways,expressionforextractsmallfootpathfromosmbyattribute,0)
outputs_QGISSAVESELECTEDFEATURES_5=processing.runalg('qgis:saveselectedfeatures', outputs_QGISSELECTBYEXPRESSION_5['RESULT'],smallfootpath)